services:
  docscraper:
    build: .
    volumes:
      - ./docs_output:/app/docs_output
      - ./logs:/app/logs
    environment:
      - URL=https://docs.browser-use.com/introduction
      - OUTPUT_DIR=docs_output
      - MAX_CONCURRENT=2
      - WAIT_TIME=5.0
    command: poetry run python main.py --url ${URL} --output-dir ${OUTPUT_DIR} --max-concurrent ${MAX_CONCURRENT} --wait-time ${WAIT_TIME}

