services:
  docscraper:
    build: .
    volumes:
      - ./docs_output:/app/docs_output
      - ./logs:/app/logs
    environment:
      - URL=https://docs.browser-use.com/introduction
      - OUTPUT_DIR=docs_output
      - MAX_CONCURRENT=2
      - MODEL_NAME=gpt-4
    command: poetry run python main.py --url ${URL} --output-dir ${OUTPUT_DIR} --max-concurrent ${MAX_CONCURRENT} --model ${MODEL_NAME}

